#!/bin/bash

if [ "$#" -lt 1 ]; then
    TAG="mavel101/bart-reco-server"
else
    TAG="$1"
fi

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

docker run -d -t --user $(id -u):$(id -g) -p 9002:9002 -v $dir:/tmp/share --rm $TAG
