#!/bin/bash

if [ "$#" -lt 1 ]; then
    TAG="bart_cuda"
else
    TAG="$1"
fi

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

docker run --gpus all -d -t --user $(id -u):$(id -g) -p 9002:9002 -v $dir:/tmp/share --rm $TAG
